### PR TITLE
Add elm-test

### PR DESCRIPTION
**Pull request by Janiczek**
This PR adds `elm-test` as of version 2.0.0.
I've been working on its reimplementation of the shrinking machinery, hence my interest in this repo :)

The version 2.0.0 is about to be released in ~14 days / after the holidays. So right now the `run.sh` script is downloading it from GitHub instead of going the usual way through the Elm package manager. Also, the library normally doesn't give the number of evaluations during shrinking, so the PR contains a patch that we apply to the library after installing that exposes that information.

### CODE REVIEW

**Comment by jlink** [comment]
@Janiczek So you want to have it merged?

**Comment by Janiczek** [comment]
I'd like that, yes, If you think nothing's missing.

I can add a new PR that simplifies the setup once the library is fully released - or we can wait until it's released and then I'll just amend this PR and we can merge it later. Both are fine with me!

**Comment by jlink** [comment]
> I'd like that, yes, If you think nothing's missing.
> 

I guess a /libraries/elm-test/README.md would be handy.

**Comment by Janiczek** [comment]
Thanks, I missed that one! Added now.

**Pull request merged**
